# Generated by Django 3.1.4 on 2020-12-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201223_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_report',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
