# Generated by Django 3.1.4 on 2020-12-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dp',
            field=models.ImageField(default='profile_pic/default.jpg', upload_to='profile_pic'),
        ),
    ]
